name: 'Build Plugin'
on:
  push:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          export ELECTRON_SKIP_BINARY_DOWNLOAD=1
          npm install -g yarn && yarn install

      - name: Build plugin
        run: yarn plugin-build

      - name: Pack plugin
        run: |
          sudo apt install zip -y
          zip -r LiteLoaderQQNT-NekoImage.zip LiteLoaderQQNT-NekoImage

      - uses: actions/upload-artifact@v4
        with:
          name: LiteLoaderQQNT-NekoImage.zip
          path: LiteLoaderQQNT-NekoImage.zip
